name: t1_job_dependecy

on:
  push:
    branches:
      - main
    
jobs:
  t1_job:
    runs-on: ubuntu-latest
    steps:
      - name:  Pausa del jobs
        run: sleep 15

  t2_job:
    runs-on: ubuntu-latest
    needs: t1_job
    steps:
      - name:  Imprimir hora y fecha
        run: date