name: t1_job_dependecy

on:
  push:
    branches:
      - qa
    
jobs:
  t1_job:
    runs-on: ubuntu-latest
    steps:
      - name:  Pausa del jobs
        run: sleep 15

  t2_job:
    runs-on: ubuntu-latest
    needs: t1_job
    steps:
      - name:  Imprimir hora y fecha
        run: date

  t3_job:
      runs-on: ubuntu-latest
      needs: t2_job
      steps:
      - name:  Imprimir msj de commit
        run: |
          echo "Mensaje de commit: ${{ github.event.head_commit.message }}"
